### ISSUE TITLE
user api failing tests after being converted to viewset

### ISSUE THREAD

**Issue by the-fool** [the-fool/woodshopio#1]
The user unit tests are failing after the change in the code.
Run manage.py test to see.
I think it is both a url route issue, and a permission issue.

**Comment by Mermadi** [comment]
rolled back my changes but the unit tests are still failing. it does seem like a url issue. going to try to switch over to generics and make the appropriate urls changes

**Comment by the-fool** [comment]
The url regex was malformed, and the endpoint lacked a name (necessary for reverse-lookups).  Now we're getting 405 -Method Not Allowed, indicating that POST and PUT aren't handled by the DRF.

**Comment by the-fool** [comment]
Tests are passing again
